name: {{cookiecutter.repo_name}}
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bash_kernel
  - biopython
  - bioservices
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - openpyxl
  - pandas
  - python
  - requests
  - ruamel.yaml
  - scipy
  - scikit-learn
  - seaborn
  - statsmodels
  - xlrd
